### ISSUE TITLE
RAS 2022 vaccine coverage case study - R companion partial draft for review

### ISSUE THREAD

**Issue by AmyMikhail** [EPIET/RapidAssessmentSurveys#1]
**Problem statement:**

I have pushed the working draft of the 2022 version of the R companion to review - the following sections are ready:

- session 1 - all tasks 
- session 2 - all tasks
- session 4 - 1st task

There is no analasys task in session 3. I will push more as I have it during the day.  It is called `RAS_R_guide_2022.Rmd` and you will find it in the `2022_dplyr_version` sub-folder.  The accompanying data tables for sessions 1 and 2 is in the `data` sub-folder.

**Proposed solution:**
@aspina7 as discussed, you can start reviewing the sections I have already completed - I will tag you here when I upload more.

**Still to do:**

1. For today: complete to end of session 4, review and knit to html (to upload on EVA tomorrow)
2. For Friday: add sessions 5 and 6 (optional extra if people are very fast with the other sessions, otherwise as ref material)
3. If possible: add all the explanatory text from the main guide so that R users only need to refer to one document.

**Comment by AmyMikhail** [comment]
@aspina7 just pushing the next version.  It has:

- All your edits for sessions 1 and 2 incorporated
- More code ready to review up to end of task 4.4

**Still to do: today:**
Task 4.5 (there are no new coding concepts, just a repeat of the already demonstrated principles on different variables and survey designs) - will finish that off this am.


1. 

1.

**Comment by aspina7** [comment]
@AmyMikhail just a quick note re {here} - you dont specify `file = ` as there are no arguments to the function, specifying file throws a warning because it then thinks you are trying to name the path file (still works but will confuse people) 

```r
> here::here(file = "data", "Sampling_frames.xlsx")
[1] "C:/Users/Spina/Desktop/RapidAssessmentSurveys/data/Sampling_frames.xlsx"
Warning:
Arguments must be unnamed 
```

**Comment by AmyMikhail** [comment]
@aspina7 thanks for that catch, think it was a typo - I'll go through and remove them.

**Comment by AmyMikhail** [comment]
@aspina7  4.5 is now there for your review, it seems to be knitting fine etc. so hopefully only minor things to check.

There is only one issue, which I will check with Kostas as well - the design effects are coming out quite differently compared to the STATA guide.  I think they may be using a different method, I've just gone with the default but can change it if someone can tell me what the STATA one is using.  For the most part it is not affecting interpretation of the overall results though, and the vaccine coverage estimates are more or less the same.
